export { thankUser as thank } from './thank.js';
export { blockUser as block } from './block.js';
export { deletePage as delete } from './delete.js';
export { movePage as move } from './move.js';
export { rollbackPage as rollback } from './rollback.js';
export { undoPage as undo } from './undo.js';
export { revertFile as filerevert } from './filerevert.js';
export const allowedAction = new Set(['thank', 'block', 'blocknotalk', 'delete', 'move', 'rollback', 'undo', 'file']);
export const commentAction = new Set(['block', 'blocknotalk', 'delete', 'move', 'rollback', 'undo', 'file']);
export const autocommentAction = new Set(['rollback', 'undo']);
export const expiryAction = new Set(['block', 'blocknotalk']);
export const thankAction = new Set(['rev', 'log']);